---
name: "afc-alarms"
description: "Get Aruba AFC alarms and load mongo databases."
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "arubafc.get_arubafc_alarms"
